# AUTOGENERATED FROM 'queries/state_attributes_get_all.edgeql' WITH:
#     $ edgedb-py --target async


from __future__ import annotations

import dataclasses
import uuid

import edgedb


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class StateAttributesGetAllResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    type: str
    default_value: str | None


async def state_attributes_get_all(
    executor: edgedb.AsyncIOExecutor,
) -> list[StateAttributesGetAllResult]:
    return await executor.query(
        """\
        select StateAttributes {
          name,
          type,
          default_value
        }
        filter .active = <bool>true;\
        """,
    )
