# AUTOGENERATED FROM 'queries/state_attributes_get_by_id.edgeql' WITH:
#     $ edgedb-py --target async


from __future__ import annotations

import dataclasses
import uuid

import edgedb
import pydantic


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class StateAttributesGetByIdResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    type: str
    default_value: str | None


async def state_attributes_get_by_id(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> StateAttributesGetByIdResult | None:
    return await executor.query_single(
        """\
        select StateAttributes {
          name,
          type,
          default_value
        }
        filter .active = <bool>true and .id = <uuid>$id;\
        """,
        id=id,
    )


class StateAttributesGetById(pydantic.BaseModel):
    id: uuid.UUID
