# AUTOGENERATED FROM 'queries/state_attributes_get_list.edgeql' WITH:
#     $ edgedb-py --target async


from __future__ import annotations

import dataclasses
import uuid

import edgedb
import pydantic


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class StateAttributesGetListResult(NoPydanticValidation):
    id: uuid.UUID


async def state_attributes_get_list(
    executor: edgedb.AsyncIOExecutor,
    *,
    start_requirements: list[uuid.UUID],
) -> list[StateAttributesGetListResult]:
    return await executor.query(
        """\
        select StateAttributes
          filter .id in std::array_unpack(<array<uuid>>$start_requirements)\
        """,
        start_requirements=start_requirements,
    )


class StateAttributesGetList(pydantic.BaseModel):
    start_requirements: list[uuid.UUID]
