# AUTOGENERATED FROM 'queries/workflow_locations_get.edgeql' WITH:
#     $ edgedb-py --target async


from __future__ import annotations

import dataclasses
import uuid

import edgedb
import pydantic


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass

        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class WorkflowLocationsGetResult(NoPydanticValidation):
    id: uuid.UUID
    locations: str | None


async def workflow_locations_get(
    executor: edgedb.AsyncIOExecutor,
    *,
    id: uuid.UUID,
) -> WorkflowLocationsGetResult | None:
    return await executor.query_single(
        """\
        select Workflow { id, locations }
        filter .id = <uuid>$id\
        """,
        id=id,
    )


class WorkflowLocationsGet(pydantic.BaseModel):
    id: uuid.UUID
